landing: #Will be landing page
    path: /
    controller: App\Controller\Landing::landingFunction

login:
  path: /login
  controller: App\Controller\Login::loginFunction

signup:
  path: /sign-up
  controller: App\Controller\SignUp::signupFunction

homepage:
  path: /homepage
  controller: App\Controller\Homepage::browseFunction