index:
    path: /
    controller: App\Controller\Login::loginFunction

login:
  path: /login
  controller: App\Controller\Login::loginFunction

signup:
  path: /sign-up
  controller: App\Controller\SignUp::signupFunction